### ISSUE TITLE
下载图片跨域

### ISSUE THREAD

**Issue by aliyoung** [newbieYoung/Simple-Screenshot#2]
在text.html里面使用simpleFO.downloadCanvasPng(canvas, 'name');出错
Tainted canvases may not be exported.
提示跨域

**Comment by aliyoung** [comment]
page-1.html 页面点击后直接报错：
index.js:688 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at SimpleForeignObject.canvasToBlob (http://172.24.65.1:8000/index.js:688:26)
    at SimpleForeignObject.downloadCanvasPng (http://172.24.65.1:8000/index.js:678:21)
    at http://172.24.65.1:8000/page/page-1.html:169:24
    at Image.img.onload (http://172.24.65.1:8000/index.js:609:9)

**Comment by newbieYoung** [comment]
暂时没精力跟这个组件。。。得过段时间

**Comment by newbieYoung** [comment]
大兄弟，整个组件完全重写了，你再看下呢。。。
